title: 哈利波特与魔法石
msgtype: markdown
# 变量: 可以记录某些变量的值、动态触发某些章节
variables: [rounds, credit, study, love, health]
# 舞台: 由不定数量的章节组成游戏本体
stages:
  "1.1":
    # 章节名称，会显示在消息标题的位置
    chapter: 序章 大难不死的男孩 
    # 本节剧情
    story: |-
      > @sender，欢迎回来魔法世界。自从德思礼夫妇一觉醒来在大门口台阶上发现他们的外甥，已经快十年过去了，女贞路却几乎没有变化。湛蓝的天空上悬着几片云朵，太阳依旧升到整洁的花园上，☀️阳光洒满他们的起居室，只有壁炉台上的照片显示出流失了多少时光。照片上的大头娃娃骑着一辆🚴自行车、乘坐🎠旋转木马、和母亲拥吻，他们的儿子达力显然已经不再是个小婴儿了。这栋房子里，🙈没有任何迹象表明这儿还住着另一个男孩。
      
      请@bot，输入“继续”阅读下一节剧情: 
      - **继续**
    # 输入选项: 关键词匹配，用户输入若含有该词，视为选择了此选项
    choices:
      # 关键词
      - keywords: [继续, 下一步, continue, next]
      # 描述: 若选项行为没有触发章节跳转，则显示描述消息
        description: ""
      # 行为: goto、none、incr、decr、calc，分别是章节跳转、无、变量自增、变量自减、变量运算
        action: [goto, calc]
        param: ["1.2", "health+10"]
  "1.2":
    chapter: 序章 悄悄消失的玻璃
    story: |-
      > 哈利波特还住在这里，住在楼梯间的壁橱下面，此刻他正在😪睡觉，但不会太久了。他的佩妮姨妈正在尖叫着叫他起床。
      
      请问@sender，哈利该⏰立即起床还是💤继续睡懒觉呢？
      - **立即起床**
      - **继续赖床**
    choices:
      - keywords: [起床, 立即]
        description: |-
          > @sender，哈利被惊醒了，姨妈又在拍着他的房门。哈利睡的并不好，还做了很多梦，虽然很想起床，但疲惫的身体好想并不听使唤…
          
          看起来倒不如: 
          - **继续赖床**
        action: none
      - keywords: [继续, 赖床, 睡觉, 懒, 忽略, 梦]
        description: ""
        action: goto
        param: "1.3"
      - keywords: [提示, hint]
        description: |-
          提示: @sender，你可以作出如下选择: 
          - **起床**: 既然佩尼姨妈已经在叫你起床了，为什么不顺从她呢？
          - **赖床**: 也许，当一个叛逆的孩子，也没有什么不好
        action: none
  "1.3":
    chapter: 序章 悄悄消失的玻璃
    story: |-
      > 哈利躺在床上，意犹未尽的回味着刚才的梦: 那是一个好梦，梦里有一辆会飞的摩托车，似乎，以前也做过同样的梦。
      > “你起来了吗？”佩妮姨妈又来到门外。
      > “快了。”哈利说。
      > “快了，那就赶紧，我要你看着🍗熏咸肉。你敢把它煎糊了试试。我要达力生日这一天都顺顺当当”
      
      请问@sender，接到了任务的哈利，现在要不要起床了呢？
      - **立即起床**
      - **继续赖床**
    choices:
      - keywords: [起床, 立即]
        description: ""
        action: goto
        param: "1.4"
      - keywords: [继续, 赖床, 睡觉, 懒, 忽略, 梦]
        description: |-
          > @sender，过生日的达力显然十分高兴，故意在楼梯上使劲地跳，震的哈利睡的壁橱里一阵落灰。\n哈利的🏥健康值-1，再不起床可不行了…
          > 当前健康值: @health

          看起来只有一个选择了: 
          - **立即起床**
        action: calc
        param: health-1
      - keywords: [提示, hint]
        description: |-
          提示: @sender，你可以作出如下选择: 
          - **起床**: 佩妮姨妈已经两次叫你起床了，再不起床可不妙
          - **赖床**: 也许，就算当一个叛逆的孩子，也没有什么不好
        action: none
  "1.4":
    chapter: 序章 悄悄消失的玻璃
    story: |-
      > @sender，哈利把一盘盘煎蛋和熏咸肉放到餐桌上，这可不容易，因为桌上已经满是礼物🎁，没有多余的地方了。
      > 但此刻正在清点礼物的达力却大发雷霆，“36，比去年少两件。”
      > 佩妮姨妈显然嗅出了危险的信号，连忙说：“你还没算上玛姬姑妈送你的礼物呢，你看，在桌子底下。今天上街我们再买两件，怎么样，宝贝，这样好了吧？”
      > 达力想了一会儿，这似乎是件困难的工作，他那胖胖的大脑袋仿佛要挤出汗珠来了：“那我就有36…37…”
      
      哈利显然知道答案，请问，这样达力就有多少件礼物了呢？
    choices:
      - keywords: ["36", "三十六"]
        description: "@sender，佩妮姨妈说上街再买两件，你显然没有算进来"
        action: none
      - keywords: ["38", "三十八"]
        description: "@sender，你算错了，要不要再重新数数看？"
        action: none
      - keywords: ["39", "三十九", "不要"]
        description: ""
        action: goto
        param: "1.5"
      - keywords: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0","三", "十"]
        description: |-
          > “笨蛋，这都不会算！我再给你一次机会”佩妮姨妈说到，她显然感觉到骄傲，因为就智商而言，虽然达力不算高，但哈利也远远比不上他。
          
          请问@sender，要不要再想想？
        action: none
  "1.5":
    chapter: 序章 悄悄消失的玻璃
    story: |-
      > “哦，”达力重重地坐下来，抓起离他最近的一只🎄礼包，“那好吧。”
      > 此时，弗农姨夫决定开车带达力去🐒动物园了。
      > “我警告你，”弗农把红得发紫的大脸凑到哈利跟前说，“⚠️小子，只要你干出一点点蠢事，那就在碗柜里一直呆到圣诞节吧！”

      哈利皱了皱眉，说: 
      - **我答应你**: 毕竟碗柜里可没有好滋味
      - **去你的吧**: 不去动物园又怎样，哈利本就不抱希望
    choices:
      - keywords: [答应, 好, 可以, ok, yes]
        description: ""
        action: goto
        param: "1.6"
      - keywords: [去你的, 不, 不行, no, fuck]
        description: |-
          > “你说什么？”弗农姨夫往哈利头上重重地捶了一拳，哈利健康值-5
          > 由于佩妮姨妈不放心哈利一个人在家，哈利一行人还是一起去了动物园
          > 当前健康值: @health

          @sender，请输入“继续”阅读下一小节的剧情:
          - **继续**
        action: calc
        param: health-5
      - keywords: [继续, 下一步, continue, next]
        description: ""
        action: goto
        param: "1.6"
  "1.6":
    chapter: 序章 悄悄消失的玻璃
    story: |-
      > 即使哈利答应弗农姨夫，他也不会相信的。问题是哈利周围常常会发生一些怪事，即使你磨破嘴皮子来解释，也是白费口舌。
      > 比如每次哈利理发回来都像没理过一样，有一次佩妮姨妈一口气把他的头发都剪光了，只留下一绺头发来“盖住他那道⚡️可怕的伤疤”。
      > 可是第二天起床的时候，他的头发又悉数长了出来，尽快他拼命辩白，可依然阻挡不了被佩妮姨妈关了一周禁闭的事实。

      @sender，可怜的哈利霉运什么时候才到头，请输入“继续”阅读下一小节:
      - **继续**
    choices:
      - keywords: [继续, 下一步, continue, next]
        description: ""
        action: goto
        param: "1.7"
  "1.7":
    chapter: 序章 悄悄消失的玻璃
    story: |-
      > 去🐒动物园的路上，弗农姨夫边开车边抱怨工作的事情。开会、银行、同事，都是他抱怨的对象。哈利说自己梦见过一辆会飞的摩托车。
      > “摩托车不会飞！”这次哈利成了他抱怨的对象，达力和佩妮姨妈哧哧的嘲笑起来。
      > 弗农一家来到了动物园的🐍爬虫馆，达力隔着玻璃、鼻子紧贴着看这盘亮闪闪的棕色Python(巨蟒)。
      > “让它动呀！”达力哼哼唧唧地央求他父亲。弗农姨夫敲了敲玻璃，可是巨蟒却纹丝不动。
      > “再敲一遍！”达力命令他父亲说。

      @sender，前方高能，请输入“继续”阅读下一小节:
      - **继续**
    choices:
      - keywords: [继续, 下一步, continue, next]
        description: ""
        action: goto
        param: "1.8"
  "1.8":
    chapter: 序章 悄悄消失的玻璃
    story: |-
      > 可是巨蟒依然继续打盹💤
      > “真烦人”，达力抱怨了一句，拖着脚慢慢走开了。
      > 哈利在后面盯着巨蟒的👀眼睛，它那眼神仿佛在对哈利说：“我总是碰到像他们这样的人。”
      
  "12.1":
    chapter: Game Over
    story: |-
      > 由于💊身负重伤，哈利在去往🏫霍格沃茨之前，很不幸地提前倒在了女贞路15号。
      > 哈利一家人，在天堂团聚了👪

      @sender，请输入“重置”来重新开始
      - **重置**
    choices: {}
# 动态条件: 输入选项结算后，会检查动态条件，若条件成立，则执行操作
dynamics:
  - conditions:
      chapter: "1.*"
      expression: health <= 0
    action: goto
    param: "12.1"
# 默认区: 当用户输入没有命中章节内所覆盖的选项时，走到这里
defaults:
  # 条件: 满足章节条件或关键词条件，则触发该默认行为
  - conditions:
      chapter: "*"
      keywords: [help, man, 帮助, 怎么玩, 你是谁]
    action: none
    description: |-
      > @sender，欢迎来到`@title`，这是一个`文字冒险游戏`，你通过输入`动作`或`指令`来推进剧情、获取帮助。
      > 几乎每个90后，都曾梦想过作为一名🔯魔法师，进入霍格沃茨的校园；都曾经想象自己置身哈利波特的剧情中，或是作出🎲改变魔法世界的决策、或是体会⛳魁地奇的欢乐、或是去充满危险的🐸禁林里冒险。
      > 现在，让我们以bot的形式，梦回童年的魔法世界，自己就是哈利，试试看你的决策，会书写出怎样的故事。
      
      游戏基本操作如下: 
      - **继续游戏**: 直接@我即可
      - **开始游戏**: start
      - **帮助**: help、man
      - **提示**: hint
      - **重置**: reset
  - conditions:
      chapter: "*"
      keywords: [hint, 提示]
    action: none
    description: "@sender，本小节没有提示😂"
  - conditions:
      chapter: "*"
      keywords: [reset, start, 重置, 回到开始, 重新开始, 开始游戏]
    action: reset
    description: "重置章节"
  - conditions:
      chapter: "*"
      keywords: []
    action: none
    description: "> 先生实在抱歉，可是你说话好像一个麻瓜🌚🌝"